USE ROLE ACCOUNTADMIN;

USE DATABASE SNOWSAMPLEAPPPKG;

DROP APPLICATION IF EXISTS SNOWSAMPLEAPP;

CREATE APPLICATION SNOWSAMPLEAPP
    FROM APPLICATION PACKAGE SNOWSAMPLEAPPPKG
    USING @CORE.CODE_STAGE
    DEBUG_MODE=TRUE;

-- name of the app comes from the setup_script saved in the app package
CALL SNOWSAMPLEAPP.APP.MYAPP();