USE ROLE ACCOUNTADMIN;

SHOW DATABASES;

DROP APPLICATION PACKAGE IF EXISTS SNOWSAMPLEAPPPKG;

DROP APPLICATION IF EXISTS SNOWSAMPLEAPP;

DROP APPLICATION PACKAGE IF EXISTS WORKINGSNOWSAMPLEAPPPKG;

DROP APPLICATION IF EXISTS WORKINGSNOWSAMPLEAPP;