USE ROLE ACCOUNTADMIN;

USE DATABASE WORKINGSNOWSAMPLEAPPPKG;

DROP APPLICATION IF EXISTS WORKINGSNOWSAMPLEAPP;

CREATE APPLICATION WORKINGSNOWSAMPLEAPP
    FROM APPLICATION PACKAGE WORKINGSNOWSAMPLEAPPPKG
    USING @CORE.CODE_STAGE
    DEBUG_MODE=TRUE;

-- name of the app comes from the setup_script saved in the app package
CALL WORKINGSNOWSAMPLEAPP.APP.MYAPP_WORKING();